apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/rugged-destiny-429602-k9/locations/us-central1-c/clusters/cluster-2

